# fly.toml app configuration file generated for 20-1-photographers-club-tlv on 2026-02-14T23:16:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = '20-1-photographers-club-tlv'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpus = 1
  memory_mb = 256

[env]
  BASE_URL = "https://20-1-photographers-club-tlv.fly.dev"

